# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20161013_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('en_id', models.IntegerField(verbose_name='ID-транкзации')),
                ('en_ps', models.CharField(max_length=50, verbose_name='Платежная система')),
                ('en_date', models.DateTimeField(verbose_name='Дата пополнения')),
                ('en_status', models.IntegerField(verbose_name='Статус платежа')),
            ],
            options={
                'verbose_name': 'Пополнения счета',
            },
        ),
    ]
