# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_enter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enter',
            name='en_ps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.PaySystems', verbose_name='Платежная система'),
        ),
        migrations.AlterField(
            model_name='enter',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Users', verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_reg',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
    ]
