# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20161013_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enter',
            name='en_status',
            field=models.IntegerField(choices=[(1, 'Первый статус'), (2, 'Второй статус')], verbose_name='Статус платежа'),
        ),
    ]
