# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20161013_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='enter',
            name='en_howmuch',
            field=models.IntegerField(default=1, verbose_name='Сума пополнения'),
            preserve_default=False,
        ),
    ]
