# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_enter_en_howmuch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enter',
            old_name='en_howmuch',
            new_name='en_sum',
        ),
    ]
