# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_auto_20161013_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='enter',
            name='en_status',
            field=models.IntegerField(choices=[(1, 'В ожидании'), (2, 'Обработано'), (3, 'Отменено')], verbose_name='Статус платежа'),
        ),
    ]
