# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_auto_20161013_1310'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Withdrawal',
        ),
        migrations.AlterField(
            model_name='users',
            name='date_reg',
            field=models.DateTimeField(verbose_name='Дата регистрации'),
        ),
    ]
