# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_auto_20161013_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enter',
            old_name='en_status',
            new_name='status',
        ),
    ]
