# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_withdrawal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawal',
            options={'verbose_name': 'Вывод средств', 'verbose_name_plural': 'Вывод средств'},
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='wd_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата пополнения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='wd_id',
            field=models.IntegerField(default=1, verbose_name='ID-транкзации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='wd_ps',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.PaySystems', verbose_name='Платежная система'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='wd_status',
            field=models.IntegerField(choices=[(1, 'В ожидании'), (2, 'Обработано'), (3, 'Отменено')], default=1, verbose_name='Статус платежа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='wd_sum',
            field=models.FloatField(default=1, verbose_name='Сума пополнения'),
            preserve_default=False,
        ),
    ]
