# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_auto_20161014_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='balance',
            field=models.FloatField(default=0.0, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_reg',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
    ]
